In [2]:
%env METAL_XCODE=1
%env DISABLE_COMPILER_CACHE=1

env: METAL_XCODE=1
env: DISABLE_COMPILER_CACHE=1


In [3]:
# first let's import the necessary libraries
import numpy as np # numpy is the main library we will use for numerical computations
import matplotlib.pyplot as plt # matplotlib is the main library we will use for plotting

# the only two libraries we will need.
from tinygrad import Tensor, dtypes # Autograd library
from tinygrad.nn.optim import Adam
from tinygrad import TinyJit

In [26]:
I = 1000000

steps = Tensor.zeros(I)
sum = Tensor.zeros(I)

for x in range(10):
    positions = Tensor(np.random.choice([-1, 1], size=(I)))
    sum += positions

# print(sum.numpy())
print(sum.numpy().mean())

0.004864


In [34]:
sum_times = Tensor.zeros(10)

limit = 10

for x in range(10):
    times = Tensor.randint(10, low=0, high=10)
    sum_times += times
    print(sum_times.numpy() < 30)
    print(sum_times.numpy())   


[ True  True  True  True  True  True  True  True  True  True]
[4. 4. 4. 5. 9. 8. 8. 0. 1. 1.]
[ True  True  True  True  True  True  True  True  True  True]
[ 8. 13.  7. 11. 11. 16. 11.  5.  5.  6.]
[ True  True  True  True  True  True  True  True  True  True]
[10. 17. 13. 11. 13. 19. 13.  5. 13. 10.]
[ True  True  True  True  True  True  True  True  True  True]
[17. 24. 14. 17. 21. 24. 19.  5. 16. 10.]
[ True  True  True  True  True  True  True  True  True  True]
[21. 28. 20. 20. 28. 25. 25.  5. 21. 17.]
[ True False  True  True False False  True  True  True  True]
[28. 36. 21. 27. 34. 30. 29.  9. 28. 26.]
[False False  True False False False False  True  True  True]
[32. 37. 23. 36. 35. 39. 30. 10. 28. 26.]
[False False False False False False False  True False  True]
[40. 45. 32. 38. 37. 46. 32. 12. 30. 27.]
[False False False False False False False  True False  True]
[44. 50. 34. 40. 46. 50. 34. 21. 39. 28.]
[False False False False False False False  True False  True]
[48. 52. 43.

In [30]:
bool_index = Tensor([True, False, True, False, True, False, True, False, True, False])

print(sum_times[bool_index].numpy())

IndexError: dtype=dtypes.bool on dim=0 is not supported, only int tensor indexing is supported